### ISSUE TITLE
Error when running app

### ISSUE THREAD

**Issue by msaron** [Kinto/kinto-react-boilerplate#25]
My environment is Centos-7. I followed the directions to install and then run. All the tests pass. I get the following error.

`ERROR in ./~/babel/polyfill.js
Module not found: Error: Cannot resolve module 'babel-core/polyfill' in /home/mana/node-apps/KINTO/kintoreact/node_modules/babel
 @ ./~/babel/polyfill.js 1:17-47
`

**Comment by msaron** [comment]
After googling the issue, I ran the following and it resolved the issue. 
`npm install babel-polyfill --save`

**Comment by leplatrem** [comment]
It should probably be added to `package.json` then!
